"""Bug fix

Revision ID: 080357b840e8
Revises: 5c17ff82eec4
Create Date: 2022-12-07 11:46:22.177749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080357b840e8'
down_revision = '5c17ff82eec4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('board', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
