"""Set default value for the task status

Revision ID: 5c17ff82eec4
Revises: 2253c11fc451
Create Date: 2022-12-06 13:34:46.553839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c17ff82eec4'
down_revision = '2253c11fc451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
